batchsize: 16 #32
epoch: 3
seed: 0
snapshot_interval: 3000
display_interval: 1000  #32,1000,0,5000,100 is default

models:
  frame_seed_generator:
    fn: models/frame_seed_generator.py
    name: FrameSeedGeneratorNoBetaInitUniform
    args:
      n_frames: 32
      z_slow_dim: 100 
      z_fast_dim: 100 
      wscale: 0.01

  video_generator:
    fn: models/video_generator.py
    name: VideoGeneratorConditionalInitUniform
    args:
      z_slow_dim: 100
      z_fast_dim: 100
      out_channels: 1
      bottom_width: 4
      wscale: 0.01

  video_discriminator:
      fn: models/video_discriminator.py
      name: VideoDiscriminatorConditionalNoBetaInitUniform
      args:
        in_channels: 2
        top_width: 4 
        mid_ch: 64
        wscale: 0.01

dataset:
  dataset_fn: datasets/hecktor_dataset.py
  dataset_name: HecktorDataset
  args:
    n_frames: 32 
    dataset_path: data/cropped_2ch_noise_0_4.npy

updater:
  fn: updaters/tgan_updater_wgan.py
  name: TGANUpdaterWGANParallelSVCCond
  args:
    freq: 5  #5
